# Generated by Django 5.2.8 on 2025-11-10 12:34

import api.apps.city
import api.apps.complaints
import api.apps.continent
import api.apps.country
import api.apps.customercreation
import api.apps.district
import api.apps.feedback
import api.apps.fuel
import api.apps.mainuserscreen
import api.apps.property
import api.apps.subproperty
import api.apps.userCreation
import api.apps.userType
import api.apps.userpermission
import api.apps.userscreen
import api.apps.vehicleCreation
import api.apps.vehicleTypeCreation
import api.apps.ward
import api.apps.wastecollection
import api.apps.zone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.continent.generate_continent_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.fuel.generate_fueltype_id, editable=False, max_length=40, unique=True)),
                ('fuel_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['fuel_type'],
            },
        ),
        migrations.CreateModel(
            name='MainUserScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.mainuserscreen.generate_mainuserscreen_id, max_length=30, unique=True)),
                ('mainscreen', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Main User Screen',
                'verbose_name_plural': 'Main User Screens',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.property.generate_propertyName_id, editable=False, max_length=40, unique=True)),
                ('property_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['property_name'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userType.generate_user_type_id, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.vehicleTypeCreation.generate_vehicle_type_id, editable=False, max_length=30, unique=True)),
                ('vehicleType', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.country.generate_country_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('mob_code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='api.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.city.generate_city_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='api.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.district.generate_district_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='api.country')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.customercreation.generate_customer_id, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('building_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('VOTER_ID', 'Voter ID'), ('PAN_CARD', 'PAN Card'), ('DL', 'Driving License'), ('PASSPORT', 'Passport')], max_length=20)),
                ('id_no', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=400, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.district')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.property')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['customer_name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='api.district'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.feedback.generate_feedback_id, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('Excellent', 'Excellent'), ('Satisfied', 'Satisfied'), ('Not Satisfied', 'Not Satisfied'), ('Poor', 'Poor')], default='Satisfied', max_length=20)),
                ('feedback_details', models.CharField(blank=True, max_length=300, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='api.customercreation')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='api.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='api.state'),
        ),
        migrations.AddField(
            model_name='customercreation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='api.state'),
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.subproperty.generate_subproperty_id, editable=False, max_length=40, unique=True)),
                ('sub_property_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_properties', to='api.property')),
            ],
            options={
                'verbose_name': 'Sub Property',
                'verbose_name_plural': 'Sub Properties',
                'ordering': ['sub_property_name'],
            },
        ),
        migrations.AddField(
            model_name='customercreation',
            name='sub_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.subproperty'),
        ),
        migrations.CreateModel(
            name='UserScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userscreen.generate_userscreen_id, max_length=30, unique=True)),
                ('screen_name', models.CharField(max_length=150)),
                ('folder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=dict)),
                ('mainscreen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userscreens', to='api.mainuserscreen')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userpermission.generate_userpermission_id, max_length=30, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('main_screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user_permissions', to='api.mainuserscreen')),
                ('user_screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions', to='api.userscreen')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions', to='api.usertype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userCreation.generate_user_id, max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.ward.generate_ward_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='api.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='api.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='api.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='api.state')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customercreation',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.ward'),
        ),
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.wastecollection.generate_wastecollection_id, max_length=30, unique=True)),
                ('wet_waste', models.FloatField(default=0.0)),
                ('dry_waste', models.FloatField(default=0.0)),
                ('mixed_waste', models.FloatField(default=0.0)),
                ('total_quantity', models.FloatField(default=0.0)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('collection_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_collections', to='api.customercreation')),
            ],
            options={
                'verbose_name': 'Waste Collection',
                'verbose_name_plural': 'Waste Collections',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.zone.generate_zone_id, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='api.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='api.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='api.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='api.state')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ward',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='api.zone'),
        ),
        migrations.CreateModel(
            name='VehicleCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.vehicleCreation.generate_vehicle_id, editable=False, max_length=30, unique=True)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('chase_no', models.CharField(blank=True, max_length=100, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fuel')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.state')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicletypecreation')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='customercreation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.zone'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.complaints.generate_complaint_id, max_length=30, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('COLLECTION', 'Collection'), ('TRANSPORT', 'Transport'), ('SEGREGATION', 'Segregation'), ('VEHICLE', 'Vehicle'), ('WORKER', 'Worker'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=api.apps.complaints.complaint_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.customercreation')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.zone')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
        migrations.AddConstraint(
            model_name='subproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('property', 'sub_property_name'), name='unique_sub_property_per_property_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user_type', 'main_screen', 'user_screen')},
        ),
    ]
