# Generated by Django 5.2.7 on 2025-10-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_type',
            field=models.CharField(max_length=100),
        ),
    ]
