# Generated by Django 5.2.7 on 2025-10-29 10:07

import api.apps.property
import api.apps.subproperty
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fuel_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.property.generate_propertyName_id, editable=False, max_length=40, unique=True)),
                ('propertyName', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['propertyName'],
            },
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.subproperty.generate_subproperty_id, editable=False, max_length=40, unique=True)),
                ('sub_property_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_properties', to='api.property')),
            ],
            options={
                'verbose_name': 'Sub Property',
                'verbose_name_plural': 'Sub Properties',
                'ordering': ['sub_property_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('property', 'sub_property_name'), name='unique_sub_property_per_property_not_deleted')],
            },
        ),
    ]
