# Generated by Django 5.2.7 on 2025-10-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_property_subproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['property_name'], 'verbose_name': 'Fuel Type', 'verbose_name_plural': 'Fuel Types'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='propertyName',
            new_name='property_name',
        ),
    ]
