# Generated by Django 5.2.7 on 2025-10-30 04:46

import api.apps.customercreation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_continent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.customercreation.generate_customer_id, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('building_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('VOTER_ID', 'Voter ID'), ('PAN_CARD', 'PAN Card'), ('DL', 'Driving License'), ('PASSPORT', 'Passport')], max_length=20)),
                ('id_no', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=400, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.district')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.property')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.state')),
                ('sub_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.subproperty')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_creation', to='api.zone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['customer_name'],
            },
        ),
    ]
