# Generated by Django 5.2.7 on 2025-10-30 09:31

import api.apps.wastecollection
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customercreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.wastecollection.generate_wastecollection_id, max_length=30, unique=True)),
                ('wet_waste', models.FloatField(default=0.0)),
                ('dry_waste', models.FloatField(default=0.0)),
                ('mixed_waste', models.FloatField(default=0.0)),
                ('total_quantity', models.FloatField(default=0.0)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('collection_time', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_collections', to='api.customercreation')),
            ],
            options={
                'verbose_name': 'Waste Collection',
                'verbose_name_plural': 'Waste Collections',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
    ]
