# Generated by Django 5.2.7 on 2025-11-03 04:04

import api.apps.feedback
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wastecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.feedback.generate_feedback_id, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('Excellent', 'Excellent'), ('Satisfied', 'Satisfied'), ('Not Satisfied', 'Not Satisfied'), ('Poor', 'Poor')], default='Satisfied', max_length=20)),
                ('feedback_details', models.CharField(blank=True, max_length=300, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='api.customercreation')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_on'],
            },
        ),
    ]
