# Generated by Django 5.2.7 on 2025-11-06 09:41

import api.apps.complaints
import api.apps.mainuserscreen
import api.apps.userCreation
import api.apps.userType
import api.apps.userpermission
import api.apps.userscreen
import api.apps.vehicleCreation
import api.apps.vehicleTypeCreation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.mainuserscreen.generate_mainuserscreen_id, max_length=30, unique=True)),
                ('mainscreen', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Main User Screen',
                'verbose_name_plural': 'Main User Screens',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userType.generate_user_type_id, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.vehicleTypeCreation.generate_vehicle_type_id, editable=False, max_length=30, unique=True)),
                ('vehicleType', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.complaints.generate_complaint_id, max_length=30, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('COLLECTION', 'Collection'), ('TRANSPORT', 'Transport'), ('SEGREGATION', 'Segregation'), ('VEHICLE', 'Vehicle'), ('WORKER', 'Worker'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=api.apps.complaints.complaint_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.customercreation')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.zone')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userscreen.generate_userscreen_id, max_length=30, unique=True)),
                ('screen_name', models.CharField(max_length=150)),
                ('folder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=dict)),
                ('mainscreen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userscreens', to='api.mainuserscreen')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userCreation.generate_user_id, max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.vehicleCreation.generate_vehicle_id, editable=False, max_length=30, unique=True)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('chase_no', models.CharField(blank=True, max_length=100, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fuel')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.state')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicletypecreation')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=api.apps.userpermission.generate_userpermission_id, max_length=30, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('main_screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user_permissions', to='api.mainuserscreen')),
                ('user_screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions', to='api.userscreen')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions', to='api.usertype')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user_type', 'main_screen', 'user_screen')},
            },
        ),
    ]
