# Generated by Django 5.2.8 on 2026-06-29 06:57

import app.models.masters.district_leader_login
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictLeaderLogin',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=app.models.masters.district_leader_login.generate_district_leader_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(help_text='Login username for the district leader.', max_length=150, unique=True)),
                ('password', models.CharField(help_text='Hashed password (Django PBKDF2).', max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('leader_name', models.CharField(blank=True, help_text='Full name of the district leader.', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District Leader Login',
                'verbose_name_plural': 'District Leader Logins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.TimeField(default=datetime.time(4, 0), help_text='Daily trip generation time in IST (HH:MM)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduler_config',
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailytripassignment',
            name='daily_trip_assignment_panchayat_xor_ward',
        ),
        migrations.RemoveConstraint(
            model_name='dailytripcollectionpoint',
            name='uniq_trip_cp_per_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='tripplan',
            name='trip_plan_panchayat_xor_ward',
        ),
        migrations.RemoveIndex(
            model_name='dailytripassignment',
            name='app_dailytr_ward_id_67a986_idx',
        ),
        migrations.RemoveField(
            model_name='collection_point',
            name='ward_id',
        ),
        migrations.RemoveField(
            model_name='dailytripassignment',
            name='ward_id',
        ),
        migrations.RemoveField(
            model_name='dailytripassignment',
            name='waste_type_id',
        ),
        migrations.RemoveField(
            model_name='tripplan',
            name='ward_id',
        ),
        migrations.RemoveField(
            model_name='vehicletypecreation',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='vehicletypecreation',
            name='project_id',
        ),
        migrations.AddField(
            model_name='collection_point',
            name='collection_type',
            field=models.CharField(choices=[('bin_collection', 'Bin Collection'), ('household_collection', 'Household Collection')], default='bin_collection', max_length=30),
        ),
        migrations.AddField(
            model_name='collection_point',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='collection_points', to='app.ward'),
        ),
        migrations.AddField(
            model_name='dailytripassignment',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='daily_trip_assignments_m2m', to='app.ward'),
        ),
        migrations.AddField(
            model_name='dailytripassignment',
            name='waste_type_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of waste type unique_ids assigned to this daily trip plan.'),
        ),
        migrations.AddField(
            model_name='project',
            name='day_wise_weighment_api_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_fcode',
            field=models.CharField(blank=True, default='VAM', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_group_name',
            field=models.CharField(blank=True, default='BLUEPLANET:VAM', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_provider_name',
            field=models.CharField(blank=True, default='BLUEPLANET', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_trip_summary_api',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_trip_user_id',
            field=models.CharField(blank=True, default='NMCP2DISPOSAL', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_user_id',
            field=models.CharField(blank=True, default='BLUEPLANET', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_vehicle_history_api',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_vehicle_tracking_api',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='trip_plans_m2m', to='app.ward'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='waste_type_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of waste type unique_ids allowed for this trip plan.'),
        ),
        migrations.AddField(
            model_name='ward',
            name='panchayat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='app.panchayat'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='property_id',
            field=models.ForeignKey(blank=True, db_column='property_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_plans', to='app.property'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='sub_property_id',
            field=models.ForeignKey(blank=True, db_column='sub_property_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_plans', to='app.subproperty'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='area_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.areatype'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyweightreport',
            unique_together={('panchayat_id', 'waste_type_id', 'month')},
        ),
        migrations.AddConstraint(
            model_name='dailytripassignment',
            constraint=models.UniqueConstraint(fields=('trip_plan_id', 'trip_date'), name='uniq_daily_trip_plan_per_date'),
        ),
        migrations.AddConstraint(
            model_name='dailytripcollectionpoint',
            constraint=models.UniqueConstraint(fields=('trip_assignment_id', 'collection_point_id', 'bin_id'), name='uniq_trip_cp_bin_per_assignment'),
        ),
        migrations.AddField(
            model_name='districtleaderlogin',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_leader_logins', to='app.company'),
        ),
        migrations.AddField(
            model_name='districtleaderlogin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='app.account'),
        ),
        migrations.AddField(
            model_name='districtleaderlogin',
            name='district_id',
            field=models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='district_leader_logins', to='app.district'),
        ),
        migrations.AddField(
            model_name='districtleaderlogin',
            name='project_id',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_leader_logins', to='app.project'),
        ),
        migrations.AddField(
            model_name='districtleaderlogin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='app.account'),
        ),
    ]
