# Generated by Django 5.2.8 on 2026-06-08 07:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_collection_point_locations(apps, schema_editor):
    for model_name in ("TripPlanCollectionPoint", "DailyTripCollectionPoint"):
        model = apps.get_model("app", model_name)
        for stop in model.objects.select_related(
            "collection_point_id",
            "collection_point_id__ward_id",
            "collection_point_id__ward_id__zone_id",
            "collection_point_id__panchayat_id",
        ).iterator():
            collection_point = stop.collection_point_id
            stop.panchayat_id = collection_point.panchayat_id
            stop.ward_id = collection_point.ward_id
            stop.zone_id = (
                collection_point.ward_id.zone_id
                if collection_point.ward_id_id
                else None
            )
            stop.save(update_fields=["panchayat_id", "ward_id", "zone_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bincollectionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytripcollectionpoint',
            name='panchayat_id',
            field=models.ForeignKey(blank=True, db_column='panchayat_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_trip_collection_points', to='app.panchayat'),
        ),
        migrations.AddField(
            model_name='dailytripcollectionpoint',
            name='ward_id',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_trip_collection_points', to='app.ward'),
        ),
        migrations.AddField(
            model_name='dailytripcollectionpoint',
            name='zone_id',
            field=models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_trip_collection_points', to='app.zone'),
        ),
        migrations.AddField(
            model_name='tripplancollectionpoint',
            name='panchayat_id',
            field=models.ForeignKey(blank=True, db_column='panchayat_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_plan_collection_points', to='app.panchayat'),
        ),
        migrations.AddField(
            model_name='tripplancollectionpoint',
            name='ward_id',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_plan_collection_points', to='app.ward'),
        ),
        migrations.AddField(
            model_name='tripplancollectionpoint',
            name='zone_id',
            field=models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_plan_collection_points', to='app.zone'),
        ),
        migrations.RunPython(
            backfill_collection_point_locations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='dailytripcollectionpoint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Collected', 'Collected'), ('Skipped', 'Skipped'), ('Missed', 'Missed')], db_index=True, default='Pending', max_length=20),
        ),
    ]
